### ISSUE TITLE
HTML Entities for Apostrophe

### ISSUE THREAD

**Issue by ghost** [uservoice/uservoice-ios-sdk#118]
Apostraphes are not properly displayed in the SDK on user comments. It does not matter if the comment originates from the SDK or from the browser.

My guess is you just need to update the HTMLEntities category for NSString.

See attached.
![image 2 ](https://f.cloud.github.com/assets/623346/184831/d44b17ac-7ced-11e2-8a06-53bf502c5731.png)

**Comment by banane** [comment]
@austintaylor I don't think it is- this is on prompt not on title, just submitted PR for it.
