### ISSUE TITLE
Can't display on Private Forum without login

### ISSUE THREAD

**Issue by DanMorganiOS** [uservoice/uservoice-ios-sdk#207]
In our app we have the ability to bring up your sdk when you are AND are not logged into our service within our private UserVoice forum.  Before updating to 3.0, we were able to get away with the following to access UserVoice without login credentials on our private forum pre v3.0:

```
ShoeboxedStyleSheet* sbxStyle = [[ShoeboxedStyleSheet alloc] init];
UVConfig *config = [UVConfig configWithSite:kUserVoiceSite
                                         andKey:kUserVoiceAPIKey
                                      andSecret:kUserVoiceSecretKey];
// Don't show Forum or post idea, because this will default to our private internal forum if they're not logged in.
    config.showPostIdea = NO;
    config.showForum = NO;
    [UVStyleSheet setStyleSheet:sbxStyle];
    [UserVoice presentUserVoiceInterfaceForParentViewController:self.viewController andConfig:config];
```

Changed the code for v3.0 of the SDK:

```
UVConfig *config = [UVConfig configWithSite:kUserVoiceSite
                                         andKey:kUserVoiceAPIKey
                                      andSecret:kUserVoiceSecretKey];

// Don't show Forum or post idea, because this will default to our internal private forum if they're not logged in.
    [self setUpUVStyleSheet];
    config.showPostIdea = NO;
    config.showForum = NO;
    [UserVoice initialize:config];

   [UserVoice presentUserVoiceInterfaceForParentViewController:self.viewController];
```

And I now receive the prompt "This application didn't configure UserVoice properly" and the following in the logs: `UserVoice SDK network error: Error Domain=uservoice Code=401 "The operation couldn’t be completed. (uservoice error 401.)" UserInfo=0x166acdd0 {message=Private forum access denied: Trusted client or authorized user required to access a private forum, type=unauthorized}`

When a user is logged in they can successfully access all of UserVoice, since I can set `identifyUserWithEmail:name:guid:` but outside our service I can not.  Even just the `presentUserVoiceContactUsFormForParentViewController:` doesn't work.  

Will this feature be available again in the future?

**Comment by pyby** [comment]
@austintaylor , I'm sorry, I fork the project and add a quick fix.
I don't take time to verify the security, but I need it.

https://github.com/pyby/uservoice-ios-sdk/commit/2f2e20355f1affcd59763ba66adb269313b17f92

Regards,

**Comment by musikhin** [comment]
Hi @pyby, 

Thanks for the quick fix.
