### ISSUE TITLE
Customizing the tint color is not working

### ISSUE THREAD

**Issue by ctalbott** [uservoice/uservoice-ios-sdk#261]
I'm implemented the sample code you have provided for customizing the tint color for the iOS SDK, [UVStyleSheet instance].tintColor = [UIColor redColor];, but it has no effect on the tint color of the userVoice interface. Am I missing something, or is this feature not working in the SDK?

**Comment by sjehutch** [comment]
I know this is very old but i thought i would post what i did here 

` let config = UVConfig(site: "company.uservoice.com")
                if let user = UserManager.sharedInstance.getCurrentUser() {
                    config.identifyUserWithEmail(user.email, name: user.firstname, guid: user.username)
                }
                UserVoice.initialize(config)
                UVStyleSheet.instance().navigationBarTintColor = UIColor.blueColor()
                UserVoice.presentUserVoiceInterfaceForParentViewController(self)
                config.showForum = true
                config.showPostIdea = true
                config.showKnowledgeBase = true
`
