### ISSUE TITLE
Viewing KB article, click Was this helpful and say yes, prompt to contact us and clicking yes doesn't pull open the contact link

### ISSUE THREAD

**Issue by VanillaSpeed** [uservoice/uservoice-ios-sdk#329]
1.  Open up an article in the app
2.  Click Yes to "Was this article helpful"
3.  You're prompted "Would you still like to contact us"
4.  You click YES but there is no result to contact support.

**Comment by austintaylor** [comment]
Figured out that this was an iPad / iOS 8 issue. Fixed in master.
