### ISSUE TITLE
The Installation Instructions are Outdated

### ISSUE THREAD

**Issue by AdamBCo** [uservoice/uservoice-ios-sdk#332]
At the moment the installation instructions are as follows:

Installation
Download the latest build.
Drag UVHeaders, UVResources, and libUserVoice.a into your project.
When adding the folders, make sure you have "Create groups for any added folders" selected rather than "Create folder references for any added folders".
Note that the .h files in UVHeaders do not need to be added to your target.
Add QuartzCore and SystemConfiguration frameworks to your project.
See DEV.md if you want to build the SDK yourself.

UVHeaders, UVResources, and libUserVoice.a do not exist in the project anymore.

Can someone please update the instructions?

Thanks

**Comment by wenpinger1221** [comment]
feiyu1221@icloud.com

**Comment by austintaylor** [comment]
Those instructions refer to the binary [builds](https://github.com/uservoice/uservoice-ios-sdk/releases) rather than the repository itself. However, the recommended install path is to use Cocoapods. I updated the readme to make this more clear.
