### ISSUE TITLE
Unable to change navigationBarBackGroundColor

### ISSUE THREAD

**Issue by AdamBCo** [uservoice/uservoice-ios-sdk#333]
At the moment I am unable to change the navigationBarBackGroundColor

My code is as follows:
    [UVStyleSheet instance].navigationBarBackgroundColor = [UIColor redColor];
    [UVStyleSheet instance].navigationBarTintColor = [UIColor blueColor];
    [UVStyleSheet instance].navigationBarTextColor = [UIColor greenColor];

The result is seen in the image attached below:
![img_0414](https://cloud.githubusercontent.com/assets/4572275/5583434/3e498992-9036-11e4-94b8-89dc41825ca5.PNG)

The solution at the moment is to find an image of the background color and use it in navigationBarBackGroundImage. It's a little inconvenient.

**Comment by davidlewisthomas** [comment]
+1

**Comment by austintaylor** [comment]
Yeah so the current behavior is just what setting navigationBar.barTintColor does. I suppose we could generate a UIImage to set instead.

**Comment by austintaylor** [comment]
Ok strike all of that. Turns out I was setting backgroundColor rather than barTintColor. Fixed in master.
