### ISSUE TITLE
[UserVoice 3.x]Redundant 'more' button displays for idea which only has 'Title'

### ISSUE THREAD

**Issue by cfzheng** [uservoice/uservoice-ios-sdk#341]
Device: iPhone4(7.0.4),iPad Air2(8.1.1)
Network: Wi-Fi
Account: N/A

Steps:
1. Tap on 'Send Feedback'
2. Tap on 'Feedback Forum'
3. Post an idea which only has 'Title'
4. Open the created idea and check
    Or you can open an idea which created before,such as name is 'T' to check

Actual result: 
Redundant 'more' button displays for idea which only has 'Title'

Expect result:
It should not display 'more' button
![img_0083](https://cloud.githubusercontent.com/assets/10428648/5640189/7733effe-965d-11e4-9c91-4e1ae3e3d46b.png)

**Comment by austintaylor** [comment]
Fixed in master.

**Comment by leileihuang** [comment]
Verify issue fixed.
Test devices: iPhone 6 (8.3), iPad air (8.0)

Thanks
Lei
