### ISSUE TITLE
[UserVoice 3.x] The ideas counter is incorrect ‘Feedback&Support’ page

### ISSUE THREAD

**Issue by cfzheng** [uservoice/uservoice-ios-sdk#344]
Device: iPhone4s(7.1.1),ipodtouch5(7.1.1)
Network: Wi-Fi
Account: N/A

Steps:
1. Tap on 'Send Feedback'
2. Check the ideas counter in ‘Feedback&Support’ page 
3. Tap on ‘Feedback Forum’
4. Back to ‘Feedback&Support’ page again and check

Actual result: 
The ideas counter show as ‘1579’ after step 3，but it will show as '144' after step 5.It is inconsistent.

Expect result:
The counter should show correctly.Could you help to check which one is correct,thanks a lot

![ss](https://cloud.githubusercontent.com/assets/10428648/5640458/b4b64dc4-9660-11e4-8adb-e1fa2b68ffaf.jpg)

**Comment by austintaylor** [comment]
This is a bug in our API. There's a cache of that number that tends to skew over time unless it gets recalculated. The SDK does a pretty good job of handling the inconsistent data it gets gracefully, but we need to fix it on the server for it to always be correct.

**Comment by austintaylor** [comment]
Closing this as the server-side bug is finally fixed.
