### ISSUE TITLE
[UserVoice 3.x] Can't search out the result when input a part of word

### ISSUE THREAD

**Issue by cfzheng** [uservoice/uservoice-ios-sdk#345]
Device: ipodtouch5(7.1.1)
Network: Wi-Fi
Account: N/A
Steps:
1.Send feedback->Feedback Forum, tap the search box.
2.Input the a part of word(eg:'onl')
3.Observed

Actual result: 
Can't search out the result

Expect result:
It should search out the correct result

![2015-01-07_11-34-27](https://cloud.githubusercontent.com/assets/10428648/5640532/82709e2c-9661-11e4-9671-420a444c7dd2.png)

**Comment by austintaylor** [comment]
Our search engine does linguistic stemming, but does not index arbitrary word prefixes.
