### ISSUE TITLE
[Question][UserVoice 3.x] What's the sort rules for ideas

### ISSUE THREAD

**Issue by cfzheng** [uservoice/uservoice-ios-sdk#346]
Device: iPhone4s(7.1.1),ipodtouch5(7.1.1)
Network: Wi-Fi
Account: N/A

Steps:
1. Tap on 'Send Feedback'-> ‘Feedback Forum’
2. Check the sort rule for ideas

Question:
What's the sort rules for ideas,now it is not sort by alphabet，ranked number and posted time.

**Comment by austintaylor** [comment]
It uses the default sort order for your account, which itself defaults to "hotness" which is a kind of hybrid of newness and number of votes. It is the same as the default sort order on your feedback site. (The only difference is that the end user cannot change the sort order.)
