### ISSUE TITLE
Unable to build for iOS 8.2 (CRITICAL)

### ISSUE THREAD

**Issue by jpike88** [uservoice/uservoice-ios-sdk#356]
Error is for YOAuthUtil.m

YOAuthUtil.m:26:47: Implicit declaration of function 'time' is invalid in 
YOAuthUtil.m:26:47: Conflicting types for 'time'

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.2.sdk/usr/include/time.h:116:8: Previous declaration is here

**Comment by austintaylor** [comment]
Are you still having issues with 8.2? It works fine for me on 8.4.
