### ISSUE TITLE
Only Spinner is Appearing

### ISSUE THREAD

**Issue by ritumobicules** [uservoice/uservoice-ios-sdk#360]
When I click on support link, available in my app, only spinner is appearing. Nothing happens. I am using iPhone4 with iOS 8.3.

**Comment by crarau** [comment]
Hi, we have the same issue.
The first time the UserVoice is displayed the Loading spinner stay forever. But if we close the page and try again it works.

The code we use: [UserVoice presentUserVoiceInterfaceForParentViewController:self];

This used to work without any problems. 
Thanks for your support,
Ciprian.

**Comment by bradrees** [comment]
I'm seeing the same behaviour on and iPhone 6 (8.3) - this is quite a severe issue.

**Comment by crarau** [comment]
Brad, I agree with you, it's critical as it makes UserVoice unaccessible.

**Comment by wlrs** [comment]
Hi everyone,

This looks like it is related to a server-side caching issue and we are working on a solution to this right now. I will keep this issue updated.

**Comment by wlrs** [comment]
Hello again,

We've made a fix on our end that, would you guys mind taking a look in your apps and letting me know if things are working reliably now? Thanks!

**Comment by ritumobicules** [comment]
Yes, Now it is working...
Thanks
