### ISSUE TITLE
UserVoice 3.2.3 preferredStatusBarStyle not working

### ISSUE THREAD

**Issue by aareeph** [uservoice/uservoice-ios-sdk#363]
I am trying to change the Status Bar color while presenting the UserVoice Interface but it seems to be not working. Please find the attached image. 

Here is my code:

[UVStyleSheet instance].preferredStatusBarStyle = UIBarStyleBlack;
[UserVoice presentUserVoiceInterfaceForParentViewController:self.tabController];

![uv_img](https://cloud.githubusercontent.com/assets/10115810/7468254/709e7708-f31f-11e4-9e23-1f88e47f0396.png)

**Comment by austintaylor** [comment]
That's the wrong enum. You want:`UIStatusBarStyleDefault` to make it black (and `UIStatusBarStyleLightContent` to make it white).
