### ISSUE TITLE
Issue config.topicId = 123;

### ISSUE THREAD

**Issue by MattiaConfalonieri** [uservoice/uservoice-ios-sdk#365]
if i config.topicId = 123; for view the knowledge of specif topic don't get all the article but only the first 10, without Load more button.

**Comment by austintaylor** [comment]
Yes, this is a bug.

**Comment by MattiaConfalonieri** [comment]
Is possible fix that?

**Comment by programmerdave** [comment]
Has this fix been released? Is this issue still open?

**Comment by MattiaConfalonieri** [comment]
Yeah is fixed...

**Comment by programmerdave** [comment]
How come the issue isn't closed then?
