### ISSUE TITLE
Do you have any instructions on how to use this with Swift?

### ISSUE THREAD

**Issue by webmagnets** [uservoice/uservoice-ios-sdk#366]
I am using Swift and would like help integrating the UserVoice SDK.

Do you have any instructions on how to use this with Swift?

**Comment by austintaylor** [comment]
We don't have an example currently. You should be able to just follow the [Swift/Objective-C interop documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-XID_25).

**Comment by seapy** [comment]
i'm using cocoapods, but i don't know how to import UserVoice

`import UserVoice` have an issue
```
AppDelegate.swift:13:8: No such module 'UserVoice'
```

Podfile
```
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
  pod 'uservoice-iphone-sdk', '~> 3.2'
end
```

**Comment by allenu** [comment]
@seapy Were you able to solve this? I'm getting the same issue even though I added UserVoice.h to the bridging header.

**Comment by andrew8712** [comment]
I'm having the same problem. 
@allenu what did you put into your bridging header to get it working?

**Comment by andrew8712** [comment]
import uservoice_iphone_sdk works.
Or #import <uservoice_iphone_sdk/UserVoice.h> in bridging header. What a stupid name of pod: "uservoice-iphone-sdk"!

**Comment by allenu** [comment]
Yeah, I had to do #import <uservoice_iphone_sdk/UserVoice.h> in the bridging header, but beyond that, you don't need to do "import UserVoice" in your Swift code.

**Comment by austintaylor** [comment]
I don't understand why you need to do `#import <uservoice_iphone_sdk/UserVoice.h>`. I made an [example repo](https://github.com/uservoice/uservoice-ios-sdk-example-swift), and it works with just `#import "UserVoice.h"`.

**Comment by andrew8712** [comment]
Your example doesn't use "use_frameworks!" directive.
