### ISSUE TITLE
Instant answers pulled from all forums

### ISSUE THREAD

**Issue by jmpilot** [uservoice/uservoice-ios-sdk#367]
In our UV demo app, I setup joeyp.uservoice.com. I have 2 forums - General and Specific.

General forum: http://joeyp.uservoice.com/forums/288284-general 
Specific forum: http://joeyp.uservoice.com/forums/299022-specific

General is the forum that is setup in the SDK: http://screencast.com/t/ryLMFJXy4 
when I type "specific" I get ideas that are in the Specific forum: http://screencast.com/t/4VvHLI38I

**Comment by austintaylor** [comment]
This is a server-side issue. Following up internally.

**Comment by bohipian** [comment]
Is there any update on this defect?  We were hoping to deploy to our mobile solution soon and have been otherwise very happy with our UserVoice experience.

**Comment by austintaylor** [comment]
@bohipian As far as I can tell this issue only affects accounts that have feedback *turned off*. Can you tell me what your account is so that I can look into it? (Or if you'd rather, you can contact UserVoice support.)

**Comment by bohipian** [comment]
Hi Austin,

Thanks for the note.  Sorry, GitHub is my personal email, our UV account
is: anytimefitness.uservoice.com

My login (and work email) is: geoffh@sebrands.com

Thanks,
Geoff
