### ISSUE TITLE
Crash - bad entry for hex_color from server

### ISSUE THREAD

**Issue by vishweshji** [uservoice/uservoice-ios-sdk#369]
In some situation (especially if we have comments on idea posted) we are getting "<null>" as value for hex_color attribute which is causing a crash.

Current we had fix this in iOS SDK code.

//          Here's the bad entry response getting from the server.
//          Printing description of statusDict:
//          {
//            "hex_color" = "<null>"; <- This is leading to crash. This object is of type NSNULL not 'nil'
//            id = 1459625;
//            key = "working-on-it";
//            name = "Working on it";
//          }

// Old code (unsafe for NSNULL type)
_statusHexColor =[statusDict objectForKey:@"hex_color”]; 

// New Code
_statusHexColor = (NSString *)[self objectOrNilForDict:statusDict key:@"hex_color"];

**Comment by austintaylor** [comment]
Fixed in master.
