### ISSUE TITLE
[UserVoice 3.x][iPhone 6+]Tutorial on post an idea page can't be shown in landscape mode.

### ISSUE THREAD

**Issue by leileihuang** [uservoice/uservoice-ios-sdk#384]
Device: iPhone6 (8.3), iPhone 6 (8.0.2), iPhone 6 plus (9.0)
Network: Wi-Fi
Account: N/A

Steps:
1. Go to LSB
2. Tap on 'Send Feedback'
3. Tap on 'Feedback Forum'
4. Tap "Post an idea".
5. Change device to landscape mode.
6. Check tutorial at post idea page.

Actual result: 
In landscape mode, tutorial can't be shown at post idea page for iPhone 6+ devices.
Expect result:
Tutorial should be shown at landscape mode also for iPhone 6+
![ss1](https://cloud.githubusercontent.com/assets/14815704/10066683/dff00c76-62c7-11e5-938f-a515ca0fa9ea.png)
![ss2](https://cloud.githubusercontent.com/assets/14815704/10066684/dff29e46-62c7-11e5-86ac-4d4087fdeb12.png)

**Comment by banane** [comment]
I have a solution for all devices listed here: Phone6 (8.3), iPhone 6 (8.0.2), iPhone 6 plus (9.0) in landscape mode. 4s devices will not see the description by design- there isn't enough room in the screen to also enter the fields.
