### ISSUE TITLE
statusColor crash

### ISSUE THREAD

**Issue by andrewbradnan** [uservoice/uservoice-ios-sdk#389]
It looks like you may have fixed this already.  If so, when do you plan on getting another release out?

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1a0f34ea8'

Last Exception Backtrace:
0   CoreFoundation                       0x0000000185084f5c __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x0000000199c77f80 objc_exception_throw + 52
2   CoreFoundation                       0x000000018508bc6c -[NSObject(NSObject) doesNotRecognizeSelector:] + 208
3   CoreFoundation                       0x0000000185088c14 ___forwarding___ + 868
4   CoreFoundation                       0x0000000184f8cdcc _CF_forwarding_prep_0 + 88
5   Groupies                             0x00000001000cc7b8 +[UVUtils parseHexColor:] (UVUtils.m:78)
6   Groupies                             0x00000001000c6194 -[UVSuggestion statusColor] (UVSuggestion.m:90)
7   Groupies                             0x00000001000b20c4 -[UVInstantAnswerManager customizeCell:forSuggestion:] (UVInstantAnswerManager.m:180)
8   Groupies                             0x00000001000bfc18 -[UVInstantAnswersViewController customizeCellForSuggestion:indexPath:] (UVInstantAnswersViewController.m:74)
9   Groupies                             0x000000010008c908 -[UVBaseViewController heightForDynamicRowWithReuseIdentifier:indexPath:] (UVBaseViewController.m:434)
10  Groupies                             0x00000001000bfcc0 -[UVInstantAnswersViewController tableView:heightForRowAtIndexPath:] (UVInstantAnswersViewController.m:79)
11  UIKit                                0x000000018a6ff278 __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke + 392
12  UIKit                                0x000000018a6be188 -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] + 3944
13  UIKit                                0x000000018a6bd144 -[UITableViewRowData rectForFooterInSection:heightCanBeGuessed:] + 408

Thanks

**Comment by banane** [comment]
When/where were you getting this crash?

**Comment by austintaylor** [comment]
Fixed
