### ISSUE TITLE
Images on knowledge base page don't scale well

### ISSUE THREAD

**Issue by yllan** [uservoice/uservoice-ios-sdk#390]
Our iOS app ([SOLDA Homepage](https://solda.io), [Download from AppStore](https://itunes.apple.com/us/app/solda/id936562264?mt=8&uo=4)) use the latest UserVoice iOS SDK (3.2.3).

The images in the knowledge base page didn't scale well. I've tested it on iOS 8 and iOS 9. 
![slack for ios upload png](https://cloud.githubusercontent.com/assets/76055/10241278/769e395c-6919-11e5-80e3-6f08e1c53f71.jpeg)

However, the android version did fit into a screen.
![screenshot_2015-10-02-15-09-28](https://cloud.githubusercontent.com/assets/76055/10241280/7a7a2982-6919-11e5-8e35-8857a70965b3.png)

According to the support team, Matt B indicate that it could be the bug of iOS SDK bug. Could you help me?

**Comment by MattiaConfalonieri** [comment]
Same issue here, i don't know why but until 4 month ago i don't have this bug.

**Comment by banane** [comment]
I have this in a PR- hopefully will bundle with next release.

**Comment by banane** [comment]
done, in master
