### ISSUE TITLE
Bump cocoapod version

### ISSUE THREAD

**Issue by karlbecker** [uservoice/uservoice-ios-sdk#400]
Hello,
I see there have been many commits to the `master` branch since January 2015, but the version which is picked up by cocoapods has never been bumped up since then.

Could you please do this so `pod install` can grab the latest changes easily?

Thanks!

**Comment by dbgrandi** [comment]
:+1:

**Comment by MattiaConfalonieri** [comment]
I agree, any fix or solution until the pod update?

**Comment by austintaylor** [comment]
Done.

**Comment by dbgrandi** [comment]
Thanks @austintaylor!
