### ISSUE TITLE
401 Error now appearing in existing apps

### ISSUE THREAD

**Issue by jmprice18** [uservoice/uservoice-ios-sdk#406]
Across our various apps, we have started getting this error in the console, and the Feedback forum never loads for a user.  This was working fine, and no code update have occurred for these apps.

> UserVoice SDK network error: Error Domain=uservoice Code=401 "(null)" UserInfo={type=unauthorized, message=Trusted client or user required}

We are using UVConfig configWithsite:andKey:andSecret:andSSOToken:

SSO appears to be successful, according to the admin portal SSO logs, but the forum never loads.

**Comment by banane** [comment]
Not sure if this is the issue, but I get the same response when my SSOToken expires. Have you tried updating them?

**Comment by jmprice18** [comment]
On the app I'm debugging, my token is good until March 24th.  We have been using 30 days token expirations, and the refreshing of the token have worked for over 1.5 years.

**Comment by banane** [comment]
Right- it's not expiration, thanks for confirming.

**Comment by banane** [comment]
Looks like the api keys for these mobile apps were not "trusted" - a checkbox on the api form- so that's been sending an unauthenticated error back whenever get /api/v1/articles is being called. We can set those to trusted for subdomains. For new apps, remember to set that as trusted right off when you create the api keys.

**Comment by jmprice18** [comment]
Hey Anna, I'm not sure which checkbox you are referring to.  According to our SSO logs (under Web Portal in our admin console), when I get the 401, I still appear on the SSO Successful log.  We are setting the Trusted flag to 'true'.

Here is a snippet from the log:
JSON
{"guid":"*****@******.com",
 "display_name":"***,
 *****",
 "email":"****@****.com",
 "expires":"2016-03-24 20:42:02",
 "trusted":"true"}

**Comment by banane** [comment]
When you configure your app on the admin site, you create an API key. In that screen, there's a "trusted" checkbox. When I went in and looked at your configuration, the API key for this app wasn't trusted. Yes- the setup here will show a successful SSO login, but the api call for articles won't work.

**Comment by jmprice18** [comment]
Can you provide the exact routing in the admin section for this option?  

I see only one check box for this, and it's already set in our Integrations > Uservoice API Key section.  

We create our SSO Tokens using C#, following the guide here: https://developer.uservoice.com/docs/single-sign-on/single-sign-on/.  In the C# token generation, we set trusted to true.

**Comment by banane** [comment]
It's not in the SSO token, but the API key- correct now it's trusted. But originally it wasn't. Are you still seeing the failure of forums to load? In answer to your question about the admin section: you're right, it's now in Integrations/Uservoice APi Keys. I think it used to be in the mobile area. The checkbox is definitely in the "integrations" section. I'm still debugging this, but having turned the trusted to "true" solved the issue.

**Comment by jmprice18** [comment]
Still seeing infinite load time on the feedback forum.  When I dismiss that view and relaunch it, it loads just fine.  I just tried 5 different apps, all going to that one uservoice subdomain.  All fail to load the very first time, then works fine the second time I try to load the feedback forums.

I'll check the console logs in the morning from the app.

**Comment by jmprice18** [comment]
Still getting the same error in the device console.  When it works trying the second time, there is no error.

**Comment by banane** [comment]
Sorry for the delay- working on something

**Comment by banane** [comment]
OK we've got some stuff about to roll out that should solve this problem.

**Comment by jmprice18** [comment]
Sounds good.  Thanks for the update.

**Comment by banane** [comment]
OK we deployed a fix to our production server so the SDK won't error in loading the first time. 

The SDK will get a new version soon that will prevent the issue. Due to some security changes, we aren't supporting retrieving the articles (knowledge base) API call without a token. Upon load, that api call was going out without a token. Later on, the same request works because the token is available. The SDK will soon reflect that logic. So in short, your apps should work. I recommend downloading the latest SDK when it's out.

**Comment by bnradvios** [comment]
The fix appeared to fix the issue we are having. I will check with others to confirm. 

Thanks for helping with this.

**Comment by jmprice18** [comment]
That was my post above. Was logged in on a test account from a recent training course. The issue appears to be fixed.  Thank you.

**Comment by banane** [comment]
glad to hear @jmprice18 I'll close this once we release the new sdk

**Comment by banane** [comment]
Fixed in 3.2.6
