### ISSUE TITLE
UISearchDisplayController has been deprecated in iOS 8

### ISSUE THREAD

**Issue by BarlowTucker** [uservoice/uservoice-ios-sdk#414]
The UserVoice SDK uses the `UISearchDisplayController` which has been deprecated as of iOS 8.  This can be verified in Apple's documentation:

> Important: UISearchDisplayController is deprecated in iOS 8. (Note that UISearchDisplayDelegate is also deprecated.) To manage the presentation of a search bar and display search results in iOS 8 and later, instead use UISearchController.

See: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UISearchDisplayController_Class/

This is not only adding compiler warnings, but introduces the risk that with upcoming releases of iOS, this project will not compile at all.

See the following screenshot as an example:
<img width="1177" alt="screen shot 2016-05-11 at 9 47 02 am" src="https://cloud.githubusercontent.com/assets/7200699/15187208/76df4c7e-175d-11e6-867d-47b64bbdfd42.png">

**Comment by paulz** [comment]
yes, it would be nice to have a version of UserVoice SDK with this warnings fixed. Or may be even a branch without support of older versions.

**Comment by BarlowTucker** [comment]
Anyone from UserVoice out there care to comment?

**Comment by banane** [comment]
Hi- thanks guys. We'll check it out.

**Comment by BarlowTucker** [comment]
@banane Any updates?

**Comment by banane** [comment]
Just got some time to work on it!

**Comment by banane** [comment]
Believe we merged a PR that fixed this issue: https://github.com/uservoice/uservoice-ios-sdk/commit/fd31deaaea0064ab653a622bfe9933e602923b00 

Please report back if it's a problem still.

**Comment by BarlowTucker** [comment]
I see that you have moved the `UISearchDisplayController` from the header file to the implementation file.  While this may hide the compiler warning (I have not been able to verify that yet), if definitely does not fix the fact that you are using a deprecated API.  

It is possible that Apple will fully end support for this class, which would leave all the apps using your API with a compiler error instead of a warning.  Please consider updating your code to use a non-deprecated class (I.E., UISearchController) or some other custom implementation that is not deprecated.
