### ISSUE TITLE
3.2.8 Carthage build broken?

### ISSUE THREAD

**Issue by ittna** [uservoice/uservoice-ios-sdk#423]
I get following linker errors

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_UVPaginationInfo", referenced from:
      objc-class-ref in UVResponseDelegate.o

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UVPaginationInfo", referenced from:
      objc-class-ref in UVResponseDelegate.o

**Comment by ittna** [comment]
Problem seems to be that UVPaginationInfo hasn't been included to UserVoiceSDK target.

**Comment by austintaylor** [comment]
Fixed in master.
