### ISSUE TITLE
Crash in v3.2.7 SDK when handling 429 / "Exceeded API Limit" error

### ISSUE THREAD

**Issue by eddiekim** [uservoice/uservoice-ios-sdk#427]
The v3.2.7 SDK crashes after handling a 429 / "Exceeded API Limit" for a request.

The issue takes place when `restConnection:didReturnResource:` reads `errors` from the response which is used as an NSError userInfo object. The problem is that `NSError errorWithDomain:code:userInfo` expects an `NSDictionary`, but the SDK passes a string. This is fine until shortly later when `UVBaseModel didReceiveError` logs the error object, which causes an unrecognized selector crash.

I have a workaround below which simply wraps `errors` in an NSDictionary if needed.

### Request

GET /api/v1/oauth/request_token.json HTTP/1.1

### Response

HTTP/1.1 429 Too Many Requests
Date: Wed, 07 Sep 2016 18:19:58 GMT
Content-Type: application/json; charset=utf-8
Status: 429 Too Many Requests
X-Frame-Options: ALLOWALL
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: must-revalidate, private, max-age=0
X-Rate-Limit-Limit: 1000
X-Rate-Limit-Remaining: 0
X-Rate-Limit-Reset: 1473272400
P3P: CP="ALL DSP COR CURa ADMa DEVa OUR IND COM NAV"
X-Rack-Cache: miss
X-Request-Id: 4b921541-5ae2-41b5-bfeb-468a7a1be97a
X-Runtime: 0.019088
Server: cloudflare-nginx
CF-RAY: 2dec2c0befea1e8f-SJC
Transfer-Encoding: chunked
Connection: Keep-alive

{"errors":"Exceeded API Limit"}

### Crashing line

```
+ (void)didReceiveError:(NSError *)error context:(UVRequestContext *)context {
    NSLog(@"UserVoice SDK network error: %@", error); // crashes here
```

### Workaround

```
- (void)restConnection:(NSURLConnection *)connection didReturnResource:(id)resource object:(id)object {
    ...
        if ([resource respondsToSelector:@selector(objectForKey:)]) {
            id errors = [resource objectForKey:@"errors"];
            if (errors && ![errors isKindOfClass:[NSDictionary class]]) {
              errors = @{ @"errors": errors };
            }
            userInfo = errors;
        }
```

**Comment by austintaylor** [comment]
Patch applied and released as [3.2.9](https://github.com/uservoice/uservoice-ios-sdk/releases/tag/3.2.9). Thanks!
