### ISSUE TITLE
dangerous bug: ignoring realloc result!

### ISSUE THREAD

**Issue by manide** [uservoice/uservoice-ios-sdk#433]
In `UVUtils.m` in the function `decode64` in line 158 you're doing a `realloc` call, but not using its result. I think this can have any sorts of weird and dangerous effects (decoding wrong data, causing crashes, having security issues, ...).

Not 100% sure what the intention of the realloc call is, but I _think_ the issue should be fixed by assigning the result to `bytes` with this line (although it's not checking for `NULL`):
`bytes = realloc(bytes, length);`

**Comment by mxcl** [comment]
Why is this not fixed? I will be recommending my client stop using this potential crasher immediately.

**Comment by andrewcl** [comment]
@manide Good catch on finding this bug! Thankfully I don't see anyplace in the SDK where that particular function is being called. In addition, I don't believe it's being exported so I don't think we'd see any side effects at the moment. 

That being said, I've made a pull request to introduce the suggested fix. I'll notify this channel once it's merged in and a new release has been triggered. Thanks again for the reporting the issue!

**Comment by andrewcl** [comment]
A pull request to remove the function entirely has been merged into the repo in order to resolve the error listed in this issue. It should be available in the next release.
