### ISSUE TITLE
iPhone-X:  UserVoice suggest a feature text field is below navigation bar

### ISSUE THREAD

**Issue by prrane** [uservoice/uservoice-ios-sdk#456]
suggest a feature text field is below navigation bar, please see the screenshot:

SDK version: 3.2.11

![uservoice-iphone-x-issue](https://user-images.githubusercontent.com/3338818/32369110-0664b82a-c0ae-11e7-8eea-32b4b6e44190.png)

**Comment by jriskin** [comment]
Any updates on this?

**Comment by wlrs** [comment]
Hi everyone,

We're working on resolving several iPhone X display issues and should have fixes ready in the next week.

**Comment by austintaylor** [comment]
Fixed in 3.2.12

**Comment by prrane** [comment]
confirmed the fix 👍
